### PR TITLE
Removed some yandere code (not all)

### PR DESCRIPTION
**Pull request by PurSnake**
Yeah, just as it says in the title. But then i will remove some of the most infuriating and useless things too :3

### CODE REVIEW

**Comment by Stefan2008Git** [comment]
Alright, thanks for help

**Comment by Stefan2008Git** [comment]
Buddy, what are you did on line 81 for StoryModeState @PurSnake ?

**Comment by PurSnake** [comment]
Oh, i forgor to put ":".
Get there yourself, it's just one symbol

**Comment by Stefan2008Git** [comment]
Alright. Im gonna when i add something new LMAO

**Comment by PurSnake** [comment]
Hehe

**Comment by Stefan2008Git** [comment]
WAIT, GRAFEX ENGINE CODER? YOOOO @PurSnake . I played your engine and it's awesome and sick man. I want to report to OS Engine they stealed assets from Grafex Engine without any credits:
1. Average MS,
2. Health bar overlay,
3. Winning icon with and without

Btw again, your engine is sick and awesome with Kade and Psych Engine mix with real Kade Engine 1.8 options!

**Pull request merged**
