### PR TITLE
shortening the countdown code

### PR DESCRIPTION
**Pull request by MemeHovy**
sound doesn't work rn

### CODE REVIEW

**Comment by Stefan2008Git** [comment]
Tell me :(? I don't really know if can be a FlxSound on flixel/system/sound or flixel/sound

**Comment by MemeHovy** [comment]
> Tell me :(? I don't really know if can be a FlxSound on flixel/system/sound or flixel/sound

I don’t know why

**Comment by MemeHovy** [comment]
that’s why I made this a draft

**Comment by Stefan2008Git** [comment]
So sound doesn't want to play?

**Comment by MemeHovy** [comment]
> So sound doesn't want to play?

no for some reason

**Comment by MemeHovy** [comment]
> > > So sound doesn't want to play?
> > 
> > 
> > no for some reason
> 
> Probably some functions for Paths.sound is missing

I'll look in debug logs

**Comment by Stefan2008Git** [comment]
> > > > So sound doesn't want to play?
> > > 
> > > 
> > > no for some reason
> > 
> > 
> > Probably some functions for Paths.sound is missing
> 
> I'll look in debug logs

Alright, but if you need to sleep, then you can to do later

**Comment by Stefan2008Git** [comment]
> > > > > So sound doesn't want to play?
> > > > 
> > > > 
> > > > no for some reason
> > > 
> > > 
> > > Probably some functions for Paths.sound is missing
> > 
> > 
> > I'll look in debug logs
> 
> Alright, but if you need to sleep, then you can to do later

Btw, when i said it's missing some functions for Paths.sound, that's mean the sound is missing

**Comment by MemeHovy** [comment]
> > > > > > So sound doesn't want to play?
> > > > > 
> > > > > 
> > > > > no for some reason
> > > > 
> > > > 
> > > > Probably some functions for Paths.sound is missing
> > > 
> > > 
> > > I'll look in debug logs
> > 
> > 
> > Alright, but if you need to sleep, then you can to do later
> 
> Btw, when i said it's missing some functions for Paths.sound, that's mean the sound is missing

alright

**Pull request merged**
