### PR TITLE
Revert "Fix resync bugs & (potentially) fix SScript compiling errors"

### PR DESCRIPTION
**Pull request by JordanSantiagoYT**
There's still compiling errors

### CODE REVIEW

**Comment by Stefan2008Git** [comment]
No @JordanSantiagoYT 
Because you need to latest Flixel versions to work. Basic Flixel versions are fine

**Comment by Stefan2008Git** [comment]
Re-bring back SScript stuff instead of Flixel stuff @JordanSantiagoYT and ``!SONG.voices`` too

**Comment by Stefan2008Git** [comment]
> Re-bring back SScript stuff instead of Flixel stuff @JordanSantiagoYT and `!SONG.voices` too

Anyways, it's compiling on
https://github.com/Stefan2008Git/FNF-SB-Engine/actions/runs/6883903776

**Comment by JordanSantiagoYT** [comment]
well we can't really bring back the !SONG.voices check because otherwise we get the same resync bugs that i mentioned in #32

**Pull request closed without merging**
